name: Publish to NuGet

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
 
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore NetsuiteRequest/netsuite-rest-csharp.csproj

    - name: Test
      env:
        CONSUMER_KEY: ${{secrets.CONSUMER_KEY}}
        CONSUMER_SECRET: ${{secrets.CONSUMER_SECRET}}
        TOKEN: ${{secrets.TOKEN}}
        TOKEN_SECRET: ${{secrets.TOKEN_SECRET}}
        REALM: ${{secrets.REALM}}
      run: dotnet test NetsuiteRequest.Tests/NetsuiteRequest.Test.csproj

    - name: Build
      run: dotnet build --no-restore --configuration Release /p:Version=${VERSION} NetsuiteRequest/netsuite-rest-csharp.csproj
      
    - name: Pack
      run: dotnet pack --no-build --output . NetsuiteRequest/netsuite-rest-csharp.csproj
  
    - name: Push to NuGet
      run: dotnet nuget push *.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json